### ISSUE TITLE
GUI not launching on Windows using 'miraclGUI' command

### ISSUE THREAD

**Issue by louispivron** [AICONSlab/MIRACL#109]
Hello, I'm using MIRACL for the first time and trying to set up everything on a local Windows machine. While the docker is working just fine giving me expected outputs for command line usage (e.g. 'miracl -h'). I'm not able to launch the GUI using 'miraclGUI' yielding instead the following error : 

```bash
qt.qpa.xcb: could not connect to display
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.

Aborted
```

Do you have any idea where that could come from ? 

I'm running Xming in the background with a multi-windows (no client) configuration. 

would really appreciate any help on this !

**Comment by anthonyprinaldi** [comment]
Hi, @louispivron thank you for your interest in the tool and for reaching out for help.

This problem occurs sometimes and has to do with X11 forwarding. I'm not familiar with Xming so I don't know how that affects the setup.

What I would suggest to do is shut down the docker container with:

```
docker compose down
```

Then let's edit the `docker-compose.yml` and add `/tmp/.X11-unix:/tmp/.X11-unix` to the `volumes` section. So it should look something like this:

```
    volumes:
      - ...
      - /tmp/.X11-unix:/tmp/.X11-unix
```

Start up the docker container again with:
```
docker compose up -d
```

Connect to the container using:
```
docker exec -it <CONTAINER_NAME> bash
```

And finally, try `miraclGUI` again. 


Please let me know if this works, or if you get a new error message. Best of luck!

**Comment by anthonyprinaldi** [comment]
Hi @louispivron . I'm glad you got the GUI working :smile:

As for the warning messages, you can ignore those. We will suppress those in a future version.

As for your question about features, ACE is not the only workflow available currently. All workflows on the tutorial page you referenced are working. You are correct that the `reg_clar` workflow only uses shell scripts and no Python files.

If you are in the GUI mode, and you navigate to `Workflows` --> `Clarity-Allen Registration` you should see a pop-up that asks you to select the Clarity directory (it may take a few seconds to open up the pop-up window). Alternatively, if you type

```
miracl flow reg_clar
```

in your terminal, you should see the same pop-up window open. To confirm that something is happening when you are running the workflow, you should see this output in your docker container:

```
 c3d path check: OK... 

 No inputs given ... running in GUI mode 

 Running Set orient with the following command: 

 miracl conv set_orient 
```
Please let me know if your docker container prints an error message or anything other than the above message.

If you do not see the pop-up, you may need to check VcXsrv to see how it deals with pop-ups, or if it notifies you that another window has opened.

**Comment by louispivron** [comment]
Also I should add that the GUI is launching properly only if those commands are run every time the docker container is being built and run : 

```bash 
export DISPLAY=$(cat /etc/resolv.conf | grep nameserver | awk '{print $2}'):0
export XAUTHORITY=$HOME/.Xauthority
```

it is a bit tedious to do it every time. Would you advice anything on that part ?

Concerning my previous request, I do see the pop up window for other tasks such as the conversion ones "Nii to Tiff" and Tiff to Nii" (which are the only tasks displayed by the GUI btw) but not for the registration. The docker container prints out 

```bash
/usr/bin/env: 'bash\r' : No such file or directory
```

and same for the command line. That's why I was assuming that some sort of python script was necessary for the pop up window to appear...

Please tell me if I'm missing something here.

**Comment by anthonyprinaldi** [comment]
I'm not too sure about those commands. Are they Windows-specific (or VcXsrv-soecific) variables that need to be added? It seems like the DISPLAY variable being set has to do with an IP address.

If you would like to avoid running those commands each time, you can add them to the end of your `~/.bashrc` so that they run every time you open your terminal. In a text editor, you can add the following to the end of your `~/.bashrc`

```bash
...
export DISPLAY=$(cat /etc/resolv.conf | grep nameserver | awk '{print $2}'):0
export XAUTHORITY=$HOME/.Xauthority
```

Do you mind sharing how you have set up your MIRACL environment? E.g., are you using WSL, did you build the docker image using `build.sh`, how are you starting the docker container, and how are you connecting to the docker container? This can help diagnose the issue.

**Comment by louispivron** [comment]
I'm not familiar with Windows OS at all but I'm using it for the purpose of the my lab, so I couldn't explain in great terms what is the true meaning behind this command, but apparently 

```bash
export DISPLAY=$(cat /etc/resolv.conf | grep nameserver | awk '{print $2}'):0
```

is necessary to allow the docker container to access the X server. The installation tutorial on Windows https://miracl.readthedocs.io/en/latest/installation/installation.html was mentioning a similar command 

```bash 
export DISPLAY=$DISPLAY:localhost:0
```

which didn't help on my case. 

Anyway, the GUI is running so that's good, but I did not solve the issue with some workflows not working and throwing error message in the terminal. 

I should provide some info regarding the way I'm using MIRACL on my machine : 

- I built the docker image using `build.sh`
- I use WSL by running `wsl` under Ubuntu distribution ( I could also use docker-desktop one instead) seen under `wsl -l -v`
- I run the command `export DISPLAY=$(cat /etc/resolv.conf | grep nameserver | awk '{print $2}'):0`
- I build the docker container with `docker compose up -d`
- I shell inside the container with `docker exec -it miracl bash`
- I then finally launch the GUI `miraclGUI`

**Comment by anthonyprinaldi** [comment]
I will test out MIRACL on my Windows system today and let you know the solution I find. My apologies I haven't used MIRACL on Windows in a while so I can't think of the solution right away.

**Comment by anthonyprinaldi** [comment]
Hi @louispivron I got it working on Windows. Here are the steps I took. All of this is performed in a WSL terminal:

1. Clone the MIRACL project with `git clone https://github.com/AICONSlab/MIRACL.git`
2. `cd MIRACL`
3. Build MIRACL using `./build.sh` (along with any options you want to pass to the build script)
4. Start Xming (don't need to adjust any settings, just click through)
5. Look into the Xming logs to see what IP address it is running at: 
![image](https://github.com/AICONSlab/MIRACL/assets/57881402/dd508153-3d85-4aa0-a010-1fd668908448)
6. Copy the IP address from the logs:
![image](https://github.com/AICONSlab/MIRACL/assets/57881402/59f36047-011d-449a-a9ee-6b9bc8df9bf1)
7. Run `export DISPLAY=<IP ADDRESS>:0` e.g., `export DISPLAY=172.19.144.1:0`
8. Run `docker compose up -d`
9. Run `docker exec -it miracl bash`
10. Run `miraclGUI`

You should see the GUI open and you can use it as you wish from there. As you click through the GUI you may see some warnings in your WSL terminal, but those can be ignored. 

Please let me know if this works for you!
