### ISSUE TITLE
segmentation workflow issue 

### ISSUE THREAD

**Issue by louloupivron** [AICONSlab/MIRACL#115]
Dear developers, 

I'm facing an issue while trying to perform the segmentation workflow to my previously registered data. 

I'm using the following parameters for segmentation : 
-> vox labels from registration (opened from another software for visualization)
![Capture-2](https://github.com/AICONSlab/MIRACL/assets/97559595/63049a80-cabe-430d-98bb-df7d77204ed9)
-> input folder (viral tracing) 
![Capture-3](https://github.com/AICONSlab/MIRACL/assets/97559595/7bb77d08-e949-43d1-87a3-cab41a4bc863)
-> seg type : virus 
-> voxel size : 25um

But when running the segmentation workflow from the GUI, even though the FIJI software opens and starts pre-processing steps (e.g. substracting background), at some point the following log windows open : 

![Capture](https://github.com/AICONSlab/MIRACL/assets/97559595/f058ffe0-716f-4fe0-bb9d-4d62e109db8c)

I was not able to solve this problem due to a lack of knowledge in Java. If you have any comments on this, I would appreciate your help. 

I'm thinking maybe the input data needs to be binarized, or maybe transformed into an 8-bit image (if so please indicate how I can do it). The vox labels image is not perfect neither and shows some discontinuities, could that be an issue as well in the segmentation process ?

EDIT : would that possibly help to use my locally installed version of ImageJ (1.53q) instead of the one specified in the Singularity file ?  

Thanks for your time !

**Comment by anthonyprinaldi** [comment]
Hi @louloupivron. Thank you for reaching out for help. We will look into the issue and get back to you ASAP.

**Comment by anthonyprinaldi** [comment]
Can you please share more information on the command you are running, your environment setup (are you using MIRACL in Docker), the OS you are running on and the hardware you are running on (e.g., RAM amount).

Can you also please share the entire error log that Fiji spits out, as well as any error message that comes directly from MIRACL. Thank you!
