### ISSUE TITLE
Include information about test data

### ISSUE THREAD

**Issue by chrisroat** [AICONSlab/MIRACL#54]
The following page references "README" files in the test data folders, which do not seem to exist.

https://miracl.readthedocs.io/en/latest/data.html

I was looking for information about the voxel size of the test data, and could not find it in the docs or within the data folder above.  Let me know if I've overlooked it somewhere!

**Comment by mgoubran** [comment]
Thanks for pointing this out @chrisroat.. sorry for my late reply.. there's an **info.txt** file under data/reg/clarity, the data was 5um isotropic. We'll update the docs to point to the right file.
