### ISSUE TITLE
Check for rotating circle credentials

### ISSUE THREAD

**Issue by vsoch** [AICONSlab/MIRACL#83]
Heyo! Just wanted to check that you rotated the circle credentials - I can see docker credentials (not the credentials just that they are there) and over xmas break Circle announced we should do this because apparently they had an incident.

**Comment by jono3030** [comment]
Hey @vsoch, thanks a lot checking in and sorry for taking so long to reply! I rotated our CircleCI GitHub OAuth tokens and replaced all context variables when CircleCI first reported the incident in December. Are those the credentials you're referring to?

On a somewhat related note, your online resources on Singularity were super helpful when I had to implement it in MIRACL's CircleCI config.yml!

**Comment by vsoch** [comment]
No worries! So all I could see two weeks ago was that the variables were defined in Circle - if you regularly change them (and have changed them since Circle was hacked end of December) then there is probably no issue (and feel free to close here).

And thank you, that is so kind! <3 I (still) love containers and I'm glad that my previous resources were helpful. Especially with Circle the configs can get a bit complex.
