### ISSUE TITLE
Build the latest MIRACL image using the build script 

### ISSUE THREAD

**Issue by Bioimaging** [AICONSlab/MIRACL#93]
Hello,

We are attempting to build the latest MIRACL image using the provided build script, as outlined in your [MIRACL installation documentation](https://miracl.readthedocs.io/en/latest/installation/installation.html) with Docker. However, we have encountered an issue.

After executing the `./build.sh` command, the process becomes stuck at the following step:
`[3/16] RUN rm -rf $(python -c` etc.
The log indicates that the process is still running with the message:
`with Building wheel for simpleitk (pyproject.toml):still running...`

Our environment is Ubuntu 23.10.1 running on a Windows 10 VirtualBox.

Could you please provide guidance on resolving this issue and ensuring the successful installation of MIRACL?

Thank you for your assistance.

**Comment by jono3030** [comment]
Hi,

Thank you for opening an issue re our Docker built!

We are currently working on a major update to MIRACL that is scheduled to be released next month. The update will introduce a number of new features and also fix some known issues including this one.

We strongly recommend to wait for this release before using MIRACL. However, if you already want to test out/explore MIRACL, you can do the following:

1. I addressed the issue you are experiencing in a separate development branch which you can download with: `git clone --branch jo-dependencies_fix https://github.com/AICONSlab/MIRACL.git MIRACL_pre_release`
2. This will create a folder called `MIRACL_pre_release` on your system and clone the MIRACL repository into it.
3. After entering the folder you can check if you are on the correct branch using: `git branch`
4. Using the `./build.sh` from here should fix the issue.

I hope this helps but again, this will not be an issue in the new release. In the meantime, let us know if you run into any problems with this quick-fix.
